/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
	@Test
	void appHasAGreeting() {
		App classUnderTest = new App();
		try {
			assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
		} catch (Exception e) {
			fail();
		}
	}
}
