/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;

class AppTest {
	@Test
	void appHasAGreeting() {
		App classUnderTest = new App();
		System.setIn(new ByteArrayInputStream("Jan".getBytes()));
		assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
	}
}
