/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tamagotchi;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;

class GameTest {
	@Test
	void appHasAGreeting() {
		Game classUnderTest = new Game();
		System.setIn(new ByteArrayInputStream("Jan".getBytes()));
		assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
	}
}
