/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class App {
	public String getGreeting() throws Exception {
		String result = "";

		Class.forName("org.h2.Driver");
		Connection conn = DriverManager.getConnection("jdbc:h2:./src/main/resources/h2Test", "", "");

		Statement stmt = conn.createStatement();

		String createQ = "CREATE TABLE IF NOT EXISTS Test"
				+ "(ID INT PRIMARY KEY AUTO_INCREMENT(1,1) NOT NULL, NAME VARCHAR(255))";
		stmt.executeUpdate(createQ);

		stmt.executeUpdate("INSERT INTO Test (NAME) VALUES('Hello World!')");
		stmt.executeUpdate("INSERT INTO Test (NAME) VALUES('Hello again!')");
		stmt.executeUpdate("INSERT INTO Test (NAME) VALUES('Bye!')");

		ResultSet selectRS = stmt.executeQuery("SELECT * FROM Test");
		while (selectRS.next()) {
			System.out.printf("%s, %s\n", selectRS.getString(1), selectRS.getString(2));
		}

		return result;
	}

	public static void main(String[] args) throws Exception {
		System.out.println(new App().getGreeting());
	}
}
